name: Go CLI for Kubernetes pod monitoring

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run Go unit tests
        run: make test

  deploy-kubernetes:
    needs: test  # Only deploy if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Start KinD cluster + deploy crashy pod
        run: make setup-kind

      - name: Run Go CLI (json output)
        run: |
          make clean
          make run

      - name: Run CLI with flags
        run: |
          make build
          ./pod-monitor -o text
          ./pod-monitor -o json -n default --min-restarts=10

      - name: Teardown KinD cluster
        if: always()
        run: make delete-kind